[[redirects]]
  from = "/api/*"
  to = "https://yorkie.dev/api/:splat"
  status = 200

[build]
  publish = "_site/"
  command = "jekyll build"
  environment = { JEKYLL_ENV = "production" }

[dev]
  publish = "_site" # If you use a _redirect file, provide the path to your static content folder
