{
 "title": "Yorkie",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "10s,20s,1m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "PushPull", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PushPull: total changes per interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max_over_time(increase(yorkie_pushpull_sent_changes_total{}[$interval])[$__interval:10s])",
     "legendFormat": "sent changes"
    },
    {
     "expr": "max_over_time(increase(yorkie_pushpull_received_changes_total{}[$interval])[$__interval:10s])",
     "legendFormat": "received changes"
    }
   ]
  },
  {
   "title": "PushPull: total operations per interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max_over_time(increase(yorkie_pushpull_sent_operations_total{}[$interval])[$__interval:10s])",
     "legendFormat": "sent operations"
    },
    {
     "expr": "max_over_time(increase(yorkie_pushpull_received_operations_total{}[$interval])[$__interval:10s])",
     "legendFormat": "received operations"
    }
   ]
  },
  {
   "title": "PushPull: snapshots bytes per interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(increase(yorkie_pushpull_snapshot_bytes_total[$interval])[$__interval:10s])",
     "legendFormat": "snapshot bytes in response packs"
    }
   ]
  },
  {
   "title": "PushPull: response seconds quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(yorkie_pushpull_response_seconds_bucket[5m])) by (le))",
     "legendFormat": "response time: 0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(yorkie_pushpull_response_seconds_bucket[5m])) by (le))",
     "legendFormat": "response time: 0.90"
    }
   ]
  },
  {
   "title": "PushPull: snapshot duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(yorkie_pushpull_snapshot_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "snapshot duration: 0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(yorkie_pushpull_snapshot_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "snapshot duration: 0.90"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "gRPC handled method total per interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(ceil(increase(grpc_server_handled_total{}[$interval]))) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC handled status total per interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(ceil(increase(grpc_server_handled_total{}[$interval]))) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Agent Version",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "expr": "yorkie_agent_version", "legendFormat": "{{agent_version}}" }
   ]
  }
 ]
}